core/urls.py
from django.urls import path
from .views import (
    HomeView,

    AboutView,
    ContactView,
    SendMailView,
    
    CategoryView,
    MyOrderView,
    WriteReviewsView,
    MyReturnsView,
    CheckoutView,
    ItemDetailView,
    OrderSummaryView,
    PaymentView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart, 
    AddCouponView,    
    RequestRefundView, 
    SearchView,
    SubmitReviews,
    )

app_name = 'core'
urlpatterns=[
    path('', HomeView.as_view(), name='item-list'),
    
    path('about/', AboutView, name='AboutUs'),
    path('contact/', ContactView, name='ContactUs'),
    path('sendmail/', SendMailView, name='SendMail'),

    path('my-orders/', MyOrderView, name='my-orders'),
    path('category/<cat_name>', CategoryView, name='category-view'),
    path('write-reviews/<ref_code>/', WriteReviewsView, name='write-reviews'),
    path('submit-review/', SubmitReviews, name='submit-reviews'),
    path('my-returns/', MyReturnsView.as_view(), name='my-returns'),
    path('order-summary/', OrderSummaryView, name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('payment/<payment_option>/', PaymentView.as_view(), name="payment"),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove_single_item_from_cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name="payment"),
    path('request-refund/', RequestRefundView.as_view(), name="request-refund"),
    path('search/', SearchView.as_view(), name="search"),
    ]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('profiles.urls')),    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_alerts.html
<div class="">
{% if messages %}
    {% for message in messages %}
		    	
		<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
			{{message}}
			<button type="button" class="close" data-dismiss='alert' aria-label='close'>
				<span aria-hidden='true'>
					&times;
				</span>
				
			</button>
		</div>
    {% endfor %}
{% endif %}
</div>

templates/partials/_bottombar.html
{% load static %}
{% load cart_template_tags %}		<!-- header-bottom-->


	<div class="header-bot">
		<div class="container">
			<div class="row header-bot_inner_wthreeinfo_header_mid">
				<!-- logo -->
				<div class="col-md-3 logo_agile">
					<h1 class="text-center">
						<a href="/" class="font-weight-bold font-italic">
							<img src="{% static 'images/logo2.png' %}" alt=" " class="img-fluid">Electro Store
						</a>
					</h1>
				</div> 
				<!-- //logo -->
				<!-- header-bot -->
				<div class="col-md-9 header mt-4 mb-md-0 mb-4">
					<div class="row">
						<!-- search -->
						<div class="col-10 agileits_search">
							<form class="form-inline" action="{% url 'core:search' %}">
								<input class="form-control mr-sm-2" type="search" placeholder="Search products by name" name="product_name" 
								value="{% if values %}{{values.product_name}}{% endif %}" 

								 aria-label="Search" required>
								<button class="btn my-2 my-sm-0" type="submit">Search</button>
							</form>
						</div>
						<!-- //search -->
						<!-- cart details -->
						<div class="col-2 top_nav_right text-center mt-sm-0 mt-2">
							<div class="wthreecartaits wthreecartaits2 cart cart box_1">
								<a href="{% url 'core:order-summary' %}">
								<button  style="height: 45px;" class="btn btn-dark">
								  <i class="fas fa-cart-arrow-down"></i> 
								  
									<span class="badge badge-light">{{request.user| cart_item_count }} </span>  
								</button>
								</a>

							</div>
						</div>
						<!-- //cart details -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- shop locator (popup) -->
	<!-- //header-bottom -->
	<!-- navigation -->
	<div class="navbar-inner">
		<div class="container">
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<div class="agileits-navi_search">
					<div class="dropdown">	
								<li style="list-style-type: none; width: 100%;" class="dropdown-toggle" data-toggle="dropdown">
									<a href="">
										<strong>All Categories</strong>
										</a>
								</li>
									<div class="dropdown-menu">

								    <div class="dropdown-item">
										<a href="{% url 'core:category-view' cat_name='Mobile' %}">Mobile</a>								    	
								    </div>

								    <div class="dropdown-item">
										<a href="{% url 'core:category-view' cat_name='Computer' %}">Computer</a>								    	
								    </div>

								    <div class="dropdown-item">
										<a href="{% url 'core:category-view' cat_name='Television' %}">Television</a>								    	
								    </div>

								    <div class="dropdown-item">
										<a href="{% url 'core:category-view' cat_name='Audio' %}">Audio</a>								    	
								    </div>

								    <div class="dropdown-item">
										<a href="{% url 'core:category-view' cat_name='LargeAppliances' %}">Large Appliances</a>								    	
								    </div>

								    <div class="dropdown-item">
										<a href="{% url 'core:category-view' cat_name='Camera' %}">Cameras</a>								    	
								    </div>
								    
								</div>
							</div>

						
						
					
				</div>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
				    aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto text-center mr-xl-5">
						<li class="nav-item mr-lg-2 mb-lg-0 mb-2">
							<a class="nav-link" href="{% url 'core:item-list' %}">Home
								<span class="sr-only">(current)</span>
							</a>
						</li>
						
						
						<li class="nav-item mr-lg-2 mb-lg-0 mb-2">
							<a class="nav-link" href="{% url 'core:AboutUs' %}">About Us</a>
						</li>
						<li class="nav-item mr-lg-2 mb-lg-0 mb-2">
							<a class="nav-link" href="/">New Arrivals</a>
						</li>
						
						<li class="nav-item">
							<a class="nav-link" href="{% url 'core:ContactUs' %}">Contact Us</a>
						</li>
					</ul>
				</div>
			</nav>
		</div>
	</div>
	<!-- //navigation -->

templates/partials/_search.html
<div class="col-lg-3 mt-lg-0 mt-4 p-lg-0">
					<div class="side-bar p-sm-4 p-3">
						<div class="search-hotel border-bottom py-2">
							<h3 class="agileits-sear-head mb-3">Search Here..</h3>
							<form action="#" method="post">
								<input type="search" placeholder="Product name..." name="search" required="">
								<input type="submit" value=" ">
							</form>
						</div>
						<!-- price -->
						<div class="range border-bottom py-2">
							<h3 class="agileits-sear-head mb-3">Price</h3>
							<div class="w3l-range">
								<ul>
									<li>
										<a href="#">Under $1,000</a>
									</li>
									<li class="my-1">
										<a href="#">$1,000 - $5,000</a>
									</li>
									<li>
										<a href="#">$5,000 - $10,000</a>
									</li>
									<li class="my-1">
										<a href="#">$10,000 - $20,000</a>
									</li>
									<li>
										<a href="#">$20,000 $30,000</a>
									</li>
									<li class="mt-1">
										<a href="#">Over $30,000</a>
									</li>
								</ul>
							</div>
						</div>
						<!-- //price -->
						<!-- discounts -->
						<div class="left-side border-bottom py-2">
							<h3 class="agileits-sear-head mb-3">Discount</h3>
							<ul>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">5% or More</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">10% or More</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">20% or More</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">30% or More</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">50% or More</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">60% or More</span>
								</li>
							</ul>
						</div>
						<!-- //discounts -->
						<!-- reviews -->
						<div class="customer-rev border-bottom left-side py-2">
							<h3 class="agileits-sear-head mb-3">Customer Review</h3>
							<ul>
								<li>
									<a href="#">
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<span>5.0</span>
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<span>4.0</span>
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star-half"></i>
										<span>3.5</span>
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<span>3.0</span>
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star-half"></i>
										<span>2.5</span>
									</a>
								</li>
							</ul>
						</div>
						<!-- //reviews -->
						<!-- electronics -->
						<div class="left-side border-bottom py-2">
							<h3 class="agileits-sear-head mb-3">Electronics</h3>
							<ul>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Accessories</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Cameras & Photography</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Car & Vehicle Electronics</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Computers & Accessories</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">GPS & Accessories</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Headphones</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Home Audio</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Home Theater, TV & Video</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Mobiles & Accessories</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Portable Media Players</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Tablets</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Telephones & Accessories</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Wearable Technology</span>
								</li>
							</ul>
						</div>
						<!-- //electronics -->
						<!-- delivery -->
						<div class="left-side border-bottom py-2">
							<h3 class="agileits-sear-head mb-3">Cash On Delivery</h3>
							<ul>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Eligible for Cash On Delivery</span>
								</li>
							</ul>
						</div>
						<!-- //delivery -->
						<!-- arrivals -->
						<div class="left-side border-bottom py-2">
							<h3 class="agileits-sear-head mb-3">New Arrivals</h3>
							<ul>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Last 30 days</span>
								</li>
								<li>
									<input type="checkbox" class="checked">
									<span class="span">Last 90 days</span>
								</li>
							</ul>
						</div>
						<!-- //arrivals -->
						<!-- best seller -->
						<div class="f-grid py-2">
							<h3 class="agileits-sear-head mb-3">Best Seller</h3>
							<div class="box-scroll">
								<div class="scroll">
									<div class="row">
										<div class="col-lg-3 col-sm-2 col-3 left-mar">
											<img src="images/k1.jpg" alt="" class="img-fluid">
										</div>
										<div class="col-lg-9 col-sm-10 col-9 w3_mvd">
											<a href="">Samsung Galaxy On7 Prime (Gold, 4GB RAM + 64GB Memory)</a>
											<a href="" class="price-mar mt-2">$12,990.00</a>
										</div>
									</div>
									<div class="row my-4">
										<div class="col-lg-3 col-sm-2 col-3 left-mar">
											<img src="images/k2.jpg" alt="" class="img-fluid">
										</div>
										<div class="col-lg-9 col-sm-10 col-9 w3_mvd">
											<a href="">Haier 195 L 4 Star Direct-Cool Single Door Refrigerator</a>
											<a href="" class="price-mar mt-2">$12,499.00</a>
										</div>
									</div>
									<div class="row">
										<div class="col-lg-3 col-sm-2 col-3 left-mar">
											<img src="images/k3.jpg" alt="" class="img-fluid">
										</div>
										<div class="col-lg-9 col-sm-10 col-9 w3_mvd">
											<a href="">Ambrane 13000 mAh Power Bank (P-1310 Premium)</a>
											<a href="" class="price-mar mt-2">$1,199.00 </a>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!-- //best seller -->
					</div>
					<!-- //product right -->
				</div>

templates/partials/_topbar.html
{% load static %}


	<!-- top-header -->
	<div class="agile-main-top">
		<div class="container-fluid">
			<div class="row main-top-w3l py-2">
				<div class="col-lg-7 header-most-top">
					<p class="text-white text-lg-left text-center">Offer Zone Top Deals & Discounts
						<i class="fas fa-shopping-cart ml-1"></i>
					</p>
				</div>
				<div class="col-lg-5 header-right mt-lg-0 mt-2">
					<!-- header lists -->
					<ul>
												
						{% if user.is_authenticated %}
							<div class="dropdown">	
								<li style="width: 100%;" class="dropdown-toggle text-white" data-toggle="dropdown">
									<a href="" class="text-white">
										<strong>{{user.username.capitalize}} Account </strong>
										</a>
								</li>
								<div class="dropdown-menu">

								    <div class="dropdown-item">
										<a href="{% url 'core:my-orders' %}">My orders</a>								    	
								    </div>
								    
								    <div class="dropdown-item">
										<a href="{% url 'core:my-returns' %}">My returns & cancellations</a>								    	
								    </div>
								    
								    
									<div class="dropdown-item">
								      
								      <a href="javascript:{document.getElementById('logout').submit()} ">&nbsp;
						                <i class="fas fa-sign-out-alt"></i> Logout
						              </a>
						              <form action="{% url 'logout' %}" method="POST" id="logout">
						                {% csrf_token %}
						                <input type="hidden">  
						              </form>

								    </div>
								</div>
							</div>


						
						
						{% else %}
						

						<li class="text-center border-right text-white">
							<a href="#" data-toggle="modal" data-target="#exampleModal" class="text-white">
								<i class="fas fa-sign-in-alt mr-2"></i> Log In </a>
						</li>
						<li class="text-center text-white">
							<a href="#" data-toggle="modal" data-target="#exampleModal2" class="text-white">
								<i class="fas fa-sign-out-alt mr-2"></i>Register </a>
						</li>

						{% endif %}


					</ul>
					<!-- //header lists -->
				</div>
			</div>
		</div>
	</div>

	<!-- modals -->
	<!-- log in -->



	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title text-center">Log In</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<form action="{% url 'login' %}" method="post">
						{% csrf_token %}
						<div class="form-group">
							<label class="col-form-label">Username</label>
							<input type="text" class="form-control" placeholder=" " name="username" required="">
						</div>
						<div class="form-group">
							<label class="col-form-label">Password</label>
							<input type="password" class="form-control" placeholder=" " name="password" required="">
						</div>
						<div class="right-w3l">
							<input type="submit" class="form-control" value="Log in">
						</div><!-- 
						<div class="sub-w3l">
							<div class="custom-control custom-checkbox mr-sm-2">
								<input type="checkbox" class="custom-control-input" id="customControlAutosizing">
								<label class="custom-control-label" for="customControlAutosizing">Remember me?</label>
							</div>
						</div> -->
						<p class="text-center dont-do mt-3">Don't have an account?
							<a href="#" data-toggle="modal" data-target="#exampleModal2">
								Register Now</a>
						</p>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- register -->
	<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">Register</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<form action="{% url 'register' %}" method="post">
						{% csrf_token %}
						<div class="form-group">
							<label class="col-form-label">First Name</label>
							<input type="text" class="form-control" placeholder=" " name="first_name" required="">
						</div>

						<div class="form-group">
							<label class="col-form-label">Last Name</label>
							<input type="text" class="form-control" placeholder=" " name="last_name" required="">
						</div>

						<div class="form-group">
							<label class="col-form-label">User Name</label>
							<input type="text" class="form-control" placeholder=" " name="username" required="">
						</div>

						<div class="form-group">
							<label class="col-form-label">Email</label>
							<input type="email" class="form-control" placeholder=" " name="email" required="">
						</div>
						<div class="form-group">
							<label class="col-form-label">Password</label>
							<input type="password" class="form-control" placeholder=" " name="password" id="password1" required="">
						</div>
						<div class="form-group">
							<label class="col-form-label">Confirm Password</label>
							<input type="password" class="form-control" placeholder=" " name="password2" id="password2" required="">
						</div>
						<div class="right-w3l">
							<input type="submit" class="form-control" value="Register">
						</div>
						<div class="sub-w3l">
							<div class="custom-control custom-checkbox mr-sm-2">
								<input type="checkbox" class="custom-control-input" id="customControlAutosizing2">
								<label class="custom-control-label" for="customControlAutosizing2" required="required">I Accept to the Terms & Conditions</label>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- //modal -->
	<!-- //top-header -->

templates/partials/order_snippet.html
          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{order_item.item.title}}</h6>
                <small class="text-muted">{{order_item.item.description}}</small>
              </div>
              <span class="text-muted">{{order_item.get_final_price}}</span>
            </li>
            {% endfor %}
            {% if order.coupon %}
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{order.coupon.code}}</small>
              </div>
              <span class="text-success">-${{order.coupon.amount}}</span>
            </li>
            {% endif %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>{{order.get_total}}</strong>
            </li>
          </ul>
          <!-- Cart -->
          {% if DISPLAY_COUPON_CODE %}
        <form class="card p-2" method="POST" action="{% url 'core:add-coupon' %}">
          {% csrf_token %}
          {{ couponform.code }}
          <div class="mt-2 input-group-append">
            <button type="submit" class="btn btn-secondary btn-md waves-effect m-0">
              Redeem
            </button>
          </div>
          
        </form>
        {% endif %}

templates/partials/rating.html
{% block extra_style %}
<style type="text/css">


.rate {
    float: left;
    height: 46px;
    padding: 0 10px;
}
.rate:not(:checked) > input {
    position:absolute;
    top:-9999px;
}
.rate:not(:checked) > label {
    float:right;
    width:1em;
    overflow:hidden;
    white-space:nowrap;
    cursor:pointer;
    font-size:30px;
    color:#ccc;
}
.rate:not(:checked) > label:before {
    content: '★ ';
}
.rate > input:checked ~ label {
    color: #ffc700;    
}
.rate:not(:checked) > label:hover,
.rate:not(:checked) > label:hover ~ label {
    color: #deb217;  
}
.rate > input:checked + label:hover,
.rate > input:checked + label:hover ~ label,
.rate > input:checked ~ label:hover,
.rate > input:checked ~ label:hover ~ label,
.rate > label:hover ~ input:checked ~ label {
    color: #c59b08;
}




}
</style>
{% endblock %}
{% block content %}
  
<!--         <div class="row">
           
            <div class="col">
                <form class="rate-form" action="{% url 'core:write-reviews' %}" method="POST" id="">
                    {% csrf_token %}
                    
                    <label class="float-left" for="comment"><b>Comment here:</b></label>

                    <textarea name="comment" class="form-control" rows="4"></textarea>

                    <div class="mt-3 col-md-12">
                    <label class="float-left" for="rating"><b>Rate it:</b></label>
                    <br>
                    <button name="rating" value="1" id="first" class="fa fa-star fa-2x my-btn"></button>
                    <button name="rating" value="2" id="second" class="fa fa-star fa-2x my-btn"></button>
                    <button name="rating" value="3" id="third" class="fa fa-star fa-2x my-btn"></button>
                    <button name="rating" value="4" id="fourth" class="fa fa-star fa-2x my-btn"></button>
                    <button name="rating" value="5" id="fifth" class="fa fa-star fa-2x my-btn"></button>

                </div>
                <button type="submit" class="btn mt-3 btn-primary">Submit</button>
                    
                </form>
                
                
            </div>
            
        </div>



 -->

 <form action="{% url 'write-reviews' %}" method="POST">

<label class="float-left" for="comment"><b>Comment here:</b></label>
    <textarea name="comment" class="form-control" rows="4"></textarea>

<label class="float-left" for="comment"><b>Rate here:</b></label>
  <br>
  <div class="rate">
    <input type="radio" id="star5" name="rate" value="5" />
    <label for="star5" title="text">5 stars</label>
    <input type="radio" id="star4" name="rate" value="4" />
    <label for="star4" title="text">4 stars</label>
    <input type="radio" id="star3" name="rate" value="3" />
    <label for="star3" title="text">3 stars</label>
    <input type="radio" id="star2" name="rate" value="2" />
    <label for="star2" title="text">2 stars</label>
    <input type="radio" id="star1" name="rate" value="1" />
    <label for="star1" title="text">1 star</label>
  </div>
<br><br>

<input type="submit" name="" value="Submit" class="btn btn-info">
</form>




{% endblock %}