core/urls.py
from django.urls import path
from .views import (
    HomeView,

    AboutView,
    ContactView,
    SendMailView,
    
    CategoryView,
    MyOrderView,
    WriteReviewsView,
    MyReturnsView,
    CheckoutView,
    ItemDetailView,
    OrderSummaryView,
    PaymentView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart, 
    AddCouponView,    
    RequestRefundView, 
    SearchView,
    SubmitReviews,
    )

app_name = 'core'
urlpatterns=[
    path('', HomeView.as_view(), name='item-list'),
    
    path('about/', AboutView, name='AboutUs'),
    path('contact/', ContactView, name='ContactUs'),
    path('sendmail/', SendMailView, name='SendMail'),

    path('my-orders/', MyOrderView, name='my-orders'),
    path('category/<cat_name>', CategoryView, name='category-view'),
    path('write-reviews/<ref_code>/', WriteReviewsView, name='write-reviews'),
    path('submit-review/', SubmitReviews, name='submit-reviews'),
    path('my-returns/', MyReturnsView.as_view(), name='my-returns'),
    path('order-summary/', OrderSummaryView, name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('payment/<payment_option>/', PaymentView.as_view(), name="payment"),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove_single_item_from_cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name="payment"),
    path('request-refund/', RequestRefundView.as_view(), name="request-refund"),
    path('search/', SearchView.as_view(), name="search"),
    ]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('profiles.urls')),    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from datetime import datetime
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES =(
        ('Mobile', 'Mobile'),
        ('Computer', 'Computer'),
        ('Television', 'Television'),
        ('Audio', 'Audio'),
        ('LargeAppliances', 'Large Appliances'),
        ('Camera', 'Camera')
    )


LABEL_CHOICES =(
        ('p', 'primary'),
        ('S', 'secondary'),
        ('D', 'danger')
        
    )


ADDRESS_CHOICES =(
        ('B', 'Billing'),
        ('S', 'Shipping'),
        
    )


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(default=0)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=15)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1,blank=True, null=True)
    is_published = models.BooleanField(default=True)
    stock = models.IntegerField(default=100)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to='photos/%Y/%m/%d')
    image_1 = models.ImageField(upload_to='photos/%Y/%m/%d')    
    image_2 = models.ImageField(upload_to='photos/%Y/%m/%d')

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse("core:product", kwargs={      # core is the namespace, and product is the name of the url.
            'slug': self.slug
            })


    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={      # core is the namespace, and add-to-cart is the name of the url.
            'slug': self.slug
            })



    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={      # core is the namespace, and remove-from-cart is the name of the url.
            'slug': self.slug
            })


    def get_price(self):
        return self.price - self.discount_price




class OrderItem(models.Model): 
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
    
    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    
    def get_total_item_price(self):
        return self.quantity * self.item.price


    def get_total_discount_item_price(self):
        return self.quantity * (self.item.price - self.item.discount_price)



    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()


    def get_final_price(self):
        if self.item.discount_price > 0:
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()



class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True) 
    items = models.ManyToManyField(OrderItem)
    item = models.ForeignKey(OrderItem, on_delete=models.CASCADE, related_name="OrderItem", blank="True", null="True")
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address= models.ForeignKey('Address', related_name="billing_address", on_delete = models.SET_NULL, blank=True, null=True)
    shipping_address= models.ForeignKey('Address', related_name="shipping_address", on_delete = models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete = models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete = models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    '''
    
    1. Item added to the cart
    2. Addnig a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delievred
    5. Received
    6. Refunds

    '''

    def __str__(self):
        return self.user.username


    def get_item_info(self):
        quantity = self.items.quantity
        return quantity


    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Comment(models.Model):
    order = models.CharField(max_length=30)
    message = models.CharField(max_length=200, blank=True, null=True)
    rating = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.order


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                            on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False, default='Pakistan')
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()
    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()
    requested_date = models.DateTimeField(default=datetime.now)

    def __str__(self):
       return f"{self.pk}"



def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/listings/contact.html
{% extends 'base.html' %}
{% load static %}
{% block extra_title %} Contact Us {% endblock %}
{% block content %}
	
	<!-- banner-2 -->
	<div class="page-head_agile_info_w3l">

	</div>
	<!-- //banner-2 -->
	<!-- page -->
	<div class="services-breadcrumb">
		<div class="agile_inner_breadcrumb">
			<div class="container">
				<ul class="w3_short">
					<li>
						<a href="index.html">Home</a>
						<i>|</i>
					</li>
					<li>Contact Us</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- //page -->

	<!-- contact -->
	<div class="contact py-sm-5 py-4">
		<div class="container py-xl-4 py-lg-2">
			<!-- tittle heading -->
			<h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
				<span>C</span>ontact
				<span>U</span>s
			</h3>
			<!-- //tittle heading -->
			<div class="row contact-grids agile-1 mb-5">
				<div class="col-sm-4 contact-grid agileinfo-6 mt-sm-0 mt-2">
					<div class="contact-grid1 text-center">
						<div class="con-ic">
							<i class="fas fa-map-marker-alt rounded-circle"></i>
						</div>
						<h4 class="font-weight-bold mt-sm-4 mt-3 mb-3">Address</h4>
						<p>1PO Box 54000
							<label>Pakistan.</label>
						</p>
					</div>
				</div>
				<div class="col-sm-4 contact-grid agileinfo-6 my-sm-0 my-4">
					<div class="contact-grid1 text-center">
						<div class="con-ic">
							<i class="fas fa-phone rounded-circle"></i>
						</div>
						<h4 class="font-weight-bold mt-sm-4 mt-3 mb-3">Call Us</h4>
						<p>+(0423) 121 121
							<label>+(0423) 121 122</label>
						</p>
					</div>
				</div>
				<div class="col-sm-4 contact-grid agileinfo-6">
					<div class="contact-grid1 text-center">
						<div class="con-ic">
							<i class="fas fa-envelope-open rounded-circle"></i>
						</div>
						<h4 class="font-weight-bold mt-sm-4 mt-3 mb-3">Email</h4>
						<p>
							<a href="mailto:info@example.com">umershuja12@gmail.com</a>
							<label>
								<a href="mailto:info@example.com">suirsan12@gmail.com</a>
							</label>
						</p>
					</div>
				</div>
			</div>
			<!-- form -->
			<form action="{% url 'core:SendMail' %}" method="POST">
				{% csrf_token %}
				<div class="contact-grids1 w3agile-6">
					<div class="row">
						<div class="col-md-6 col-sm-6 contact-form1 form-group">
							<label class="col-form-label">Name</label>
							<input type="text" class="form-control" name="Name" placeholder="" required="">
						</div>
						<div class="col-md-6 col-sm-6 contact-form1 form-group">
							<label class="col-form-label">E-mail</label>
							<input type="email" class="form-control" name="Email" placeholder="" required="">
						</div>
					</div>
					<div class="contact-me animated wow slideInUp form-group">
						<label class="col-form-label">Message</label>
						<textarea name="Message" class="form-control" placeholder="" required=""> </textarea>
					</div>
					<div class="contact-form">
						<input type="submit" value="Submit">
					</div>
				</div>
			</form>
			<!-- //form -->
		</div>
	</div>
	<!-- //contact -->

	<!-- map -->
	<div class="map mt-sm-0 mt-4">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d805196.5077734194!2d144.49270863101745!3d-37.97015423820711!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad646b5d2ba4df7%3A0x4045675218ccd90!2sMelbourne+VIC%2C+Australia!5e0!3m2!1sen!2sin!4v1474020956974"
		    allowfullscreen></iframe>
	</div>
	<!-- //map -->

	<!-- middle section -->
	<div class="join-w3l1 py-sm-5 py-4">
		<div class="container py-xl-4 py-lg-2">
			<div class="row">
				<div class="col-lg-6">
					<div class="join-agile text-left p-4">
						<div class="row">
							<div class="col-sm-7 offer-name">
								<h6>Smooth, Rich & Loud Audio</h6>
								<h4 class="mt-2 mb-3">Branded Headphones</h4>
								<p>Sale up to 25% off all in store</p>
							</div>
							<div class="col-sm-5 offerimg-w3l">
								<img src="{% static 'images/off1.png' %}" alt="" class="img-fluid">
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-6 mt-lg-0 mt-5">
					<div class="join-agile text-left p-4">
						<div class="row ">
							<div class="col-sm-7 offer-name">
								<h6>A Bigger Phone</h6>
								<h4 class="mt-2 mb-3">Smart Phones 5</h4>
								<p>Free shipping order over $100</p>
							</div>
							<div class="col-sm-5 offerimg-w3l">
								<img src="{% static 'images/off2.png' %}" alt="" class="img-fluid">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- middle section -->
	
{% endblock content %}

templates/listings/order_summary.html
{% extends 'base.html' %}
{% block extra_title %}
Order Summary
{% endblock %}

{% block content %}
	<div class="container mt-5">
	<div class="table-responsive text-nowrap">
  		<h2>Order Summary</h2>
  		<table class="table mt-4">
  			<thead>
  				<tr>
  					<th scope="col">#</th>
  					<th scope="col">Item title</th>
  					<th scope="col">Price</th>
  					<th scope="col">Quantity</th>
  					<th scope="col">Total Item price</th>
  				</tr>
  			</thead>
  			<tbody>
  				
  				{% for order_item in object.items.all %}
  				<tr>
	  				<th scope="row">{{ forloop.counter }}</th>
	  				<td> {{ order_item.item.title }} </td>
	  				<td> {{order_item.item.get_price}} </td>
	  				<td>
	  					<a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a> 
	  						{{ order_item.quantity }} 
	  					<a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i> </a>
	  				</td>
	  				<td> 
	  					{% if order_item.item.discount_price %}
	  						{{ order_item.get_total_discount_item_price }}
	  						<span class="badge badge-primary">Saving ${{order_item.get_amount_saved}} </span>
	  					{% else %}
	  						{{ order_item.get_total_item_price }}
	  					{% endif %}
	 					<a style="color:red;" href="{% url 'core:remove-from-cart' order_item.item.slug %}"><i class="fas fa-trash float-right"></i></a>

	  				</td>
	  			</tr>
	  			{% empty %}
	  			<tr>
	  				<td colspan="5">Your cart is empty</td>
	  			</tr>
	  			<tr>
	  				<td colspan="5">
	  					<a class="btn btn-primary float-right" href="/">Continue Shopping</a>
	  				</td>
	  			</tr>
	  			{% endfor %}

	  			{% if object.coupon %}
	  			<tr>
	  				<td colspan="4"><b>Coupon</b></td>
	  				<td><b> -${{ object.coupon.amount }}</b> </td>
	  			</tr>
	  			{% endif %}

	  			
	  			{% if object.get_total %}
	  			<tr>
	  				<td colspan="4"><b>Grand total:</b></td>
	  				<td> <b>{{object.get_total}}</b> </td>
	  			</tr>
	  			<tr>
	  				<td colspan="5">
	  					<a class="btn btn-warning float-right ml-2" href="{% url 'core:checkout' %}">Proceed to checkout</a>
	  					<a class="btn btn-primary float-right" href="/">Continue shopping</a>
	  				</td>
	  			</tr>
	  			{% endif %}
	  			

  			</tbody>
  		</table>
	</div>
</div>
{% endblock %}

templates/listings/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- banner-2 -->
	<div class="page-head_agile_info_w3l">

	</div>
	<!-- //banner-2 -->
	<!-- page -->
	<div class="services-breadcrumb">
		<div class="agile_inner_breadcrumb">
			<div class="container">
				<ul class="w3_short">
					<li>
						<a href="index.html">Home</a>
						<i>|</i>
					</li>
					<li>Electronics</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- //page -->

	<!-- top Products -->
	<div class="ads-grid py-sm-5 py-4">
		<div class="container py-xl-4 py-lg-2">
			<!-- tittle heading -->
			<h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
				{{cat_name}}</h3>
			<!-- //tittle heading -->
		
			{% if items %}

			<div class="row">
								{% for item in items %}
									{% if item.stock > 0 %}
								<div class="col-md-3 product-men mt-5">
									<div class="men-pro-item simpleCart_shelfItem">
										<div class="men-thumb-item text-center">
											<img height="200" width="160" src="{{ item.image.url }}" alt="">
											<div class="men-cart-pro">
												<div class="inner-men-cart-pro">
													<a href="{{ item.get_absolute_url}}" class="link-product-add-cart">Quick View</a>
												</div>
											</div>
											
											
										</div>
										<div class="item-info-product text-center border-top mt-4">
											<a href="" class="grey-text">
												<h5>{{item.get_category_display}}</h5>
											</a>
											<h4 class="pt-1">
												<a href="{{item.get_absolute_url}}">{{item.title}}
													

												</a>
											</h4>
											<div class="info-product-price my-2">
												<span class="item_price">Rs. {{item.get_price}}/-</span>
												{% if item.discount_price %}
												<del> {{item.price}} </del>
												{% endif %}
											</div>
											</div>
										</div>
									</div>
									{% endif %}
								
								
								{% endfor %}
							</div>
							{% else %}
							<p>no such items</p>
							{% endif %}



			
		</div>
	<!-- //top products -->

	<!-- middle section -->
	<div class="join-w3l1 py-sm-5 py-4">
		<div class="container py-xl-4 py-lg-2">
			<div class="row">
				<div class="col-lg-6">
					<div class="join-agile text-left p-4">
						<div class="row">
							<div class="col-sm-7 offer-name">
								<h6>Smooth, Rich & Loud Audio</h6>
								<h4 class="mt-2 mb-3">Branded Headphones</h4>
								<p>Sale up to 25% off all in store</p>
							</div>
							<div class="col-sm-5 offerimg-w3l">
								<img src="images/off1.png" alt="" class="img-fluid">
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-6 mt-lg-0 mt-5">
					<div class="join-agile text-left p-4">
						<div class="row ">
							<div class="col-sm-7 offer-name">
								<h6>A Bigger Phone</h6>
								<h4 class="mt-2 mb-3">Smart Phones 5</h4>
								<p>Free shipping order over $100</p>
							</div>
							<div class="col-sm-5 offerimg-w3l">
								<img src="images/off2.png" alt="" class="img-fluid">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- middle section -->

	{% endblock content %}

templates/listings/search.html
{% extends 'base.html' %}

{% block extra_title %}
Search Result
{% endblock %}
{% block content %}


	<div class="ads-grid py-sm-5 py-4">
		<div class="container py-xl-4 py-lg-2">
			<!-- tittle heading -->
			<h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
				<!-- <span>O</span>ur
				<span>N</span>ew
				<span>P</span>roducts --> </h3> 
			<!-- //tittle heading -->
			<div class="row">
				<!-- product left -->
				<div class="agileinfo-ads-display col-lg-12">
					<div class="wrapper">
						<!-- first section -->
						<div class="product-sec1 px-sm-4 px-3 py-sm-5  py-3 mb-4">
							<h3 class="heading-tittle text-center font-italic">
								
							</h3>
							
							<div class="row">
								{% if search_item %}  
								{% for item in search_item %}
								<div class="col-md-3 product-men mt-5">
									<div class="men-pro-item simpleCart_shelfItem">
										<div class="men-thumb-item text-center">
											<img height="200" width="160" src="{{ item.image.url }}" alt="">
											<div class="men-cart-pro">
												<div class="inner-men-cart-pro">
													<a href="{{ item.get_absolute_url}}" class="link-product-add-cart">Quick View</a>
												</div>
											</div>
											<span class="product-new-top {{item.get_label_display}}-color">New</span>
										</div>
										<div class="item-info-product text-center border-top mt-4">
											<a href="" class="grey-text">
												<h5>{{item.get_category_display}}</h5>
											</a>
											<h4 class="pt-1">
												<a href="{{item.get_absolute_url}}">{{item.title}}
													

												</a>
											</h4>
											<div class="info-product-price my-2">
												<span class="item_price">Rs. {{item.get_price}} /-</span>
												{% if item.discount_price %}
												<del> {{item.price}} </del>
												{% endif %}
											</div>
											</div>
										</div>
									</div>
								
								
								{% endfor %}
								{% else %}
								<p>No such item available!</p>
								{% endif %}

							</div>
								
					</div>
				</div>
				<!-- //product left -->


			</div>
			<section>
				{% if is_paginated %}
				<nav class="d-flex justify-content-center wow fadeIn">
				  <ul class="pagination pg-blue">
				  	{% if page_obj.has_previous %}
				  	<!-- Previous error -->
				    <li class="page-item">
				      <a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
				        <span aria-hidden="true">&laquo;</span>
				        
				      </a>
				    </li>
				    {% endif %}


				    <li class="page-item active">
				    	<a class="page-link" href="{{page_obj.number}}">{{page_obj.number}}</a>
				    </li>


				    	{% if page_obj.has_next %}
				    <!-- Next arrow -->

				    <li class="page-item">
				      <a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
				        <span aria-hidden="true">&raquo;</span>
				      </a>
				    </li>
				    {% endif %}
				  </ul>
				</nav>
				{% endif %}
			</section>
		</div>
	</div>
	<!-- //top products -->
	</div>




{% endblock %}

templates/listings/write_reviews.html
{% extends 'base.html' %}
{% block extra_title %}write reviews{% endblock %}

{% block extra_style %}
<style type="text/css">


.rate {
    float: left;
    height: 46px;
    padding: 0 10px;
}
.rate:not(:checked) > input {
    position:absolute;
    top:-9999px;
}
.rate:not(:checked) > label {
    float:right;
    width:1em;
    overflow:hidden;
    white-space:nowrap;
    cursor:pointer;
    font-size:30px;
    color:#ccc;
}
.rate:not(:checked) > label:before {
    content: '★ ';
}
.rate > input:checked ~ label {
    color: #ffc700;    
}
.rate:not(:checked) > label:hover,
.rate:not(:checked) > label:hover ~ label {
    color: #deb217;  
}
.rate > input:checked + label:hover,
.rate > input:checked + label:hover ~ label,
.rate > input:checked ~ label:hover,
.rate > input:checked ~ label:hover ~ label,
.rate > label:hover ~ input:checked ~ label {
    color: #c59b08;
}




}


	
.order-item .item-pic img {
    width: 80px;
    height: 80px;
}

.order {
    margin-top: 12px;
    padding-bottom: 24px;
    background-color: #fff;
}

img {
    border-style: none;
    /*vertical-align: middle;*/
}

.clear {
    clear: both;
}

.order-item {
    min-height: 80px;
    margin: 24px 12px 24px 36px;
    padding-right: 12px;
    width: 916px;
}

.order-item .item-title {
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2;
}

.text.title {
    font-size: 14px;
    margin-bottom: 3px;
}

.text {
    color: #212121;
    word-break: break-word;
}
.border{
	border: 1px;
}

.button1{
	background-color: white;
	text-align: center;
	color:black;
	width: 50%;
}


</style>

{% endblock %}



{% block content %}




<div class="container">
<div class="mt-4 border lzd-playground-right">
        <div class="breadcrumb">
            <a class="first " href="//my.daraz.pk/customer/order/index/">Write Reviews</a>
        </div>

        <div id="container" class="container">
        	<div>
        	<div class="order-list">
        		
        		<div class="orders">
        			<div class="order">
        				<div class="order-info">
        					<div class="float-left">
                                {% if order %}
                                {% for odr in order %}
        						<div class="info-order-left-text">Order# 
        							<a href="#" class="link"> {{ odr.ref_code }}</a>
        						</div>
                                
        						<p class="text info desc">Placed on {{odr.start_date}}</p>
        					</div>
        					<div class="pull-cont"></div>
        					
                            <a href="{% url 'core:request-refund' %}" class="float-right link manage" style="color: rgb(26, 156, 183);">Refund Request</a>
        					<div class="clear"></div>
        				</div>
        				
 						<hr>
 						       				
        				<div class="order-item">
        					<div class="row">
        					<div class="col-md-1 item-pic" data-spm="detail_image">
        						<a href="#">
        							<img width="50" height="50" src="{{odr.item.item.image.url}}">
        						</a>

        					</div>
        					<div style="border-right: 1px solid black;" class="col-md-4 item-main item-main-mini">
        						
	        						<div class="text title item-title" data-spm="details_title">&nbsp;{{odr.item.item.title}}</div>
	        						<p class="text desc"></p>
	        						<p class="text desc bold"></p>
	        					
        					</div>
        					<div class="col-md-7 mt-3">
                                <center>
                                
                                     <form action="{% url 'core:submit-reviews' %}" method="POST">
                                        {% csrf_token %}

                                        <input type="hidden" name="ref_code" value="{{ odr.ref_code }}">

                                    <label class="float-left" for="comment"><b>Comment here:</b></label>
                                        <textarea name="comment" class="form-control" rows="4"></textarea>

                                    <label class="float-left" for="comment"><b>Rate here:</b></label>
                                      <br>
                                      <div class="rate">
                                        <input type="radio" id="star5" name="rating" value="5" />
                                        <label for="star5" title="text">5 stars</label>
                                        <input type="radio" id="star4" name="rating" value="4" />
                                        <label for="star4" title="text">4 stars</label>
                                        <input type="radio" id="star3" name="rating" value="3" />
                                        <label for="star3" title="text">3 stars</label>
                                        <input type="radio" id="star2" name="rating" value="2" />
                                        <label for="star2" title="text">2 stars</label>
                                        <input type="radio" id="star1" name="rating" value="1" />
                                        <label for="star1" title="text">1 star</label>
                                      </div>
                                    <br><br>

                                    <input type="submit" name="" value="Submit" class="btn btn-info">
                                    </form>

	        					</center>
                                
	        				</div>
        				<div class="clear"></div>
        			</div>
        			</div>
        		</div>

        		<hr>

        	</div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
    </div>



</div>





{% endblock %}